# This Secret manages environment variables for the example2 pod.
# Typically unencrypted secrets such as this one, would not be stored in a git repository.
apiVersion: v1
kind: Secret
metadata:
  name: example2-env
  namespace: default
type: Opaque
stringData:
  db_username: staging
  db_password: super-secret-special-password
  message: Thank you for watching!
