# This Secret manages files in the /app/config directory for the example2 pod.
# Typically unencrypted secrets such as this one, would not be stored in a git repository.
apiVersion: v1
kind: Secret
metadata:
  name: example2-config
  namespace: default
type: Opaque
data:
  # An example sensitive config file, that might be read by an application.
  # This content; value is base64-encoded.
  api.json: ewogICJhcGlfaG9zdCI6ICJhcGkiLAogICJhcGlfdXNlcm5hbWUiOiAicHJvZHVjdGlvbiIsCiAgImFwaV9wYXNzd29yZCI6ICJ5YXk0cHJvZCIKfQo=
