apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.4
        resources:
          # These are unreasonably low to be able to run in my demo cluster.
          requests:
            memory: 5Mi
            cpu: 10m
          limits:
            memory: 128Mi
            cpu: 20m
        ports:
        - containerPort: 80
