# This values file was used to upgrade Fairwinds Polaris.
# Commands used in the video:
# ### First requires the fairwinds-stable Helm repo has been added, from install-polaris.sh
# helm fetch fairwinds-stable/polaris
# helm upgrade polaris --values my-values.yaml ./polaris
#
# A modified Polaris values file. . .
webhook:
  enable: true

# The full Polaris config must be specified to change any of the configuration.
config: |
  resources:
    # This next line was changed during the video.
    cpuRequestsMissing: error
    cpuLimitsMissing: warning
    memoryRequestsMissing: warning
    memoryLimitsMissing: warning
  images:
    tagNotSpecified: error
  healthChecks:
    readinessProbeMissing: warning
    livenessProbeMissing: warning
  networking:
    hostNetworkSet: warning
    hostPortSet: warning
  security:
    hostIPCSet: error
    hostPIDSet: error
    notReadOnlyRootFileSystem: warning
    privilegeEscalationAllowed: error
    runAsRootAllowed: warning
    runAsPrivileged: error
    capabilities:
      error:
        ifAnyAdded:
          - SYS_ADMIN
          - NET_ADMIN
          - ALL
      warning:
        ifAnyAddedBeyond:
          - CHOWN
          - DAC_OVERRIDE
          - FSETID
          - FOWNER
          - MKNOD
          - NET_RAW
          - SETGID
          - SETUID
          - SETFCAP
          - SETPCAP
          - NET_BIND_SERVICE
          - SYS_CHROOT
          - KILL
          - AUDIT_WRITE
  controllers_to_scan:
    - Deployments
    - StatefulSets
    - DaemonSets
    - Jobs
    - CronJobs
    - ReplicationControllers

